config/routes.rb
Rails.application.routes.draw do
  root 'risks#stats'
  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :risks do
    collection do
      post :import
      get :export
      post :export
      get :stats
      post :stats
    end
  end
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/risk.rb
class Risk < ApplicationRecord
  enum type: {
      internal: 'Внутренний',
      external: 'Внешний'
  }
  enum category: {
      c41: 'Понимание организации и ее контекста',
      c42: 'Понимание потребностей и ожиданий заинтересованных сторон',
      c43: 'Определение области применения системы менеджмента качества',
      c44: 'Система менеджмента качества и ее процессы',
      c51: 'Лидерство и приверженность',
      c52: 'Политика',
      c53: 'Роли, обязанности и полномочия в организации',
      c61: 'Действия по рассмотрению рисков и возможностей',
      c62: 'Цели в области качества и планирование их достижения',
      c63: 'Планирование изменений',
      c71: 'Ресурсы',
      c72: 'Компетентность',
      c73: 'Осведомленность',
      c74: 'Коммуникации',
      c81: 'Документированная информация',
      c82: 'Требования к продукции и услугам',
      c83: 'Проектирование и разработка продукции и услуг',
      c84: 'Управление предоставляемыми извне процессами, продукцией и услугами',
      c85: 'Предоставление продукции и услуг',
      c86: 'Выпуск продукции и услуг',
      c87: 'Управление несоответствующими выходами',
      c9: 'Оценивание пригодности',
      c10: 'Улучшение'
  }

  belongs_to :user

  def self.open_file(file)
    case File.extname(file.original_filename)
      when ".csv" then Roo::CSV.new(file.path, csv_options: { encoding: Encoding::UTF_8 })
      when ".xls" then Roo::Excel.new(file.path, xls_options: { encoding: Encoding::UTF_8 })
      when ".xlsx" then Roo::Excelx.new(file.path, xlsx_options: { encoding: Encoding::UTF_8 })
      else raise "Unknown file type: #{file.original_filename}"
    end
  end

  def self.to_csv(options = {})
    attributes = %w{category name danger_rate origin_type occured_at description}
    CSV.generate(encoding: Encoding::WINDOWS_1251) do |csv|
      csv << attributes
      all.each do |risk|
        csv << risk.attributes.values_at(*attributes)
      end
    end
  end

  def self.import(file, user_id: 1)
    attributes = %w{category name danger_rate origin_type occured_at description}
    opened_file = open_file(file)
    (1..opened_file.last_row).each do |i|
      row = opened_file.row(i)
      Risk.create! attributes.zip(row).to_h.merge(user_id: user_id)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :risks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  layout 'application_clean'

  before_action :configure_permitted_parameters, :only => [:create]

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :name, :surname) }
  end
end

app/controllers/risks_controller.rb
class RisksController < ApplicationController
  before_action :set_risk, only: [:destroy, :show, :edit, :update]
  before_action :risks_filtered_by_date, only: [:export, :stats]
  before_action :risks_filtered_by_user, only: [:export, :stats]

  def index
    @risks = Risk.all.order(created_at: :desc).page(params[:page]).per(15)
  end

  def new
    @risk = Risk.new
  end

  def create
    @risk = Risk.create(risk_params.merge(user_id: current_user.id))
    redirect_to risks_path
  end

  def destroy
    @risk.destroy
    redirect_to risks_path, notice: 'Риск был успешно удален.'
  end

  def export
    respond_to do |format|
      format.html
      format.csv do
        send_data @risks.to_csv, filename: 'risks.csv'
      end
      format.xls {
        response.headers['Content-Disposition'] = 'attachment; filename="risks.xls"'
      }
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="risks.xlsx"'
      }
    end
  end

  def show
  end

  def edit
  end

  def update
    @risk.update(risk_params)
    redirect_to risks_path
  end

  def import
    Risk.import(params[:file], user_id: current_user.id)
    redirect_to risks_path, notice: "Данные успешно загружены!"
  end

  def stats
    respond_to do |format|
      format.html
    end
  end

  private
  def set_risk
    @risk = Risk.includes(:user).find(params[:id])
  end

  def risk_params
    params.require(:risk).permit(:name, :description, :category,
    :occured_at, :danger_rate, :origin_type)
  end

  def risks_filtered_by_date
    if empty_date?(params[:start_date]) && empty_date?(params[:end_date])
      @risks = Risk.all
    elsif empty_date?(params[:start_date])
      @risks = Risk.where("occured_at <= ?", params[:end_date])
    elsif empty_date?(params[:end_date])
      @risks = Risk.where("occured_at >= ?", params[:start_date])
    else
      @risks = Risk.where(occured_at: params[:start_date]..params[:end_date])
    end
  end

  def empty_date? date
    (date.nil? || !date.present?) ? true : false
  end

  def risks_filtered_by_user
    if params[:only_my_risks].present?
      @risks = @risks.where(user_id: current_user.id)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  layout 'application_clean'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def svg(name)
    file_path = "#{Rails.root}/app/assets/images/#{name}.svg"
    return File.read(file_path).html_safe if File.exists?(file_path)
    '(not found)'
  end
end

app/helpers/risks_helper.rb
module RisksHelper
  def scatter_data
    arr = []
    @risks.group_by {|i| i.category}.each do |k, v|
      hsh = { name: k, data: [v.group_by {|it| it.danger_rate }] }
      hsh[:data].each do |item|
        item.each do |key, val|
          item[key] = val.count
        end
      end
      hsh[:data].map! { |i| i.to_a }
      hsh[:data].flatten!(1)
      hsh[:data].each { |i| i.reverse!}
      arr << hsh
    end
    arr.each { |item| item[:name] = Risk.categories[item[:name]]}
  end

  def line_chart_data
    hash = @risks.group(:origin_type).group_by_day(:occured_at).count.each do |k, v|
      k[0] == 'external' ? k[0] = 'Внешний' : k[0] = 'Внутренний'
    end
    hash
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rmis</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag "http://code.highcharts.com/highcharts.js", "chartkick" %>
    <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= render '/shared/navbar' %>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application_clean.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rmis</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <div class="container" style="margin-top: 50px">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= image_tag 'logo.svg', style: 'max-width: 600px;' %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/risks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1>Редактировать риск</h1>
      <%= form_for @risk do |f| %>
          <div class="field">
            <%= f.label 'Название' %><br>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="field">
            <%= f.label 'Описание' %><br>
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <div class="field">
            <%= f.label 'Категория' %><br>
            <%= f.select :category, options_for_select(Risk.categories.map {|k, v| [v.humanize.capitalize, k]}, class: 'form-control') %>
          </div>

          <div class="field">
            <%= f.label 'Дата' %><br>
            <%= f.date_field :occured_at, class: 'form-control' %>
          </div>

          <div class="field">
            <%= f.label 'Уровень опасности' %><br>
            <%= f.number_field :danger_rate, class: 'form-control' %>
          </div>

          <div class="field">
            <%= f.label 'Источник риска' %><br>
            <%= f.select :origin_type, options_for_select(Risk.types.map {|k, v| [v.humanize.capitalize, k]}, class: 'form-control') %>
          </div>
          <br>
          <%= f.submit "Сохранить", class: 'btn btn-primary btn-block' %>
      <% end %>
    </div>
  </div>
</div>

app/views/risks/export.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">category</Data></Cell>
        <Cell><Data ss:Type="String">name</Data></Cell>
        <Cell><Data ss:Type="String">danger_rate</Data></Cell>
        <Cell><Data ss:Type="String">origin_type</Data></Cell>
        <Cell><Data ss:Type="String">occured_at</Data></Cell>
        <Cell><Data ss:Type="String">description</Data></Cell>
      </Row>
      <% @risks.each do |risk| %>
          <Row>
            <Cell><Data ss:Type="String"><%= risk.category %></Data></Cell>
            <Cell><Data ss:Type="String"><%= risk.name %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= risk.danger_rate %></Data></Cell>
            <Cell><Data ss:Type="String"><%= risk.origin_type %></Data></Cell>
            <Cell><Data ss:Type="String"><%= risk.occured_at %></Data></Cell>
            <Cell><Data ss:Type="String"><%= risk.description %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/risks/index.html.erb
<div class="container">
  <div class="row">
    <% @risks.each do |risk| %>
        <div class="col-md-4">
          <div class="card" style="padding: 10px; margin: 8px;">
            <div class="card-block">
              <h4 class="card-title"><%= link_to risk.name, risk_path(risk), style: "text-decoration:none" %></h4>
              <h6 class="card-subtitle mb-2 text-muted"><%= Risk.categories[risk.category] %></h6>
              <p class="card-text truncate"><%= risk.description %></p>
              <div align="right">
                <%= link_to risk_path(risk), style: "text-decoration:none" do %>
                    <span style="font-size:1.2em; padding: 2px;" class="glyphicon glyphicon-eye-open"></span>
                <% end %>
                <% if !current_user.nil? && risk.user_id == current_user.id %>
                  <%= link_to edit_risk_path(risk), style: "text-decoration:none" do %>
                      <span style="font-size:1.2em; padding: 2px;" class="glyphicon glyphicon-edit"></span>
                  <% end %>
                  <%= link_to risk, method: :delete, style: "text-decoration:none" do %>
                      <span style="font-size:1.2em; padding: 2px;" class="glyphicon glyphicon-trash"></span>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

<div style="padding: 10px; margin: 8px;">
  <%= paginate @risks %>
</div>

app/views/risks/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">category</Data></Cell>
        <Cell><Data ss:Type="String">name</Data></Cell>
        <Cell><Data ss:Type="String">danger_rate</Data></Cell>
        <Cell><Data ss:Type="String">origin_type</Data></Cell>
        <Cell><Data ss:Type="String">occured_at</Data></Cell>
        <Cell><Data ss:Type="String">description</Data></Cell>
      </Row>
      <% @risks.each do |risk| %>
          <Row>
            <Cell><Data ss:Type="String"><%= risk.category %></Data></Cell>
            <Cell><Data ss:Type="String"><%= risk.name %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= risk.danger_rate %></Data></Cell>
            <Cell><Data ss:Type="String"><%= risk.origin_type %></Data></Cell>
            <Cell><Data ss:Type="String"><%= risk.occured_at %></Data></Cell>
            <Cell><Data ss:Type="String"><%= risk.description %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/risks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1>Добавить новый риск</h1>
      <%= form_for @risk do |f| %>
          <div class="field">
            <%= f.label 'Название' %><br>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="field">
            <%= f.label 'Описание' %><br>
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <div class="field">
            <%= f.label 'Категория' %><br>
            <%= f.select :category, options_for_select(Risk.categories.map {|k, v| [v.humanize.capitalize, k]}, class: 'form-control') %>
          </div>

          <div class="field">
            <%= f.label 'Дата' %><br>
            <%= f.date_field :occured_at, class: 'form-control' %>
          </div>

          <div class="field">
            <%= f.label 'Уровень опасности' %><br>
            <%= f.number_field :danger_rate, class: 'form-control' %>
          </div>

          <div class="field">
            <%= f.label 'Источник риска' %><br>
            <%= f.select :origin_type, options_for_select(Risk.types.map {|k, v| [v.humanize.capitalize, k]}, class: 'form-control') %>
          </div>
          <br>
          <%= f.submit "Создать", class: 'btn btn-primary btn-block' %>
      <% end %>
    </div>
    <div class="col-md-3">
      <div class="row">
        <div class="card" style="padding: 10px; margin: 8px;">
          <div class="card-block">
            <h1>Импортировать данные из файла</h1>
            <h4>CSV / XLS / XLSX</h4>
            <%= form_tag import_risks_path, multipart: true do %>
                <%= file_field_tag :file %><br>
                <%= submit_tag "Импортировать", class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/risks/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-2">
    <div>
      <h1 align="center"><%= @risk.name %></h1>
      <h3 align="center" style="color: GrayText"><%= Risk.categories[@risk.category] %></h3>
      <div class="row">
        <div>Описание: </div>
        <div><%= @risk.description %></div>
      </div>
      <div class="row">
        <div>Дата происшествия: </div>
        <div><%= @risk.occured_at %></div>
      </div>

      <div class="row">
        <div>Уровень риска: </div>
        <div><%= @risk.danger_rate %></div>
      </div>
      <div class="row">
        <div>Источник риска: </div>
        <div><%= Risk.types[@risk.origin_type] %></div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="card" style="padding: 10px; margin: 8px;">
      <div class="card-block">
        <h2 class="card-title" align="center">Автор риска:</h2>
        <div class="col-md-4">
          <% if @risk.user.avatar.nil? %>
              <%= image_tag 'default_avatars/man128.png', class: 'img-responsive' %>
          <% else %>
              <%= image_tag @risk.user.avatar, class: 'img-responsive' %>
          <% end %>
        </div>
        <div class="col-md-8">
          <h3><%= @risk.user.name %></h3>
          <h3><%= @risk.user.surname %></h3>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/risks/stats.html.erb
  <div class="row">
    <div class="col-md-9">
      <div class="card" style="padding: 10px; margin: 8px;">
        <div class="card-block">
          <h2 align="center">Распределение по дате</h2>
          <%= line_chart @risks.group_by_day(:occured_at).count, xtitle: "Дата", ytitle: "Количество", height: '400px' %>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div align="center">
        <%= form_tag("/", method: "get") do %>
            <div class="card" style="padding: 10px; margin: 8px;">
              <div class="card-block">
                <div style="padding: 5px">
                  <%= label_tag 'Начальная дата' %><br>
                  <%= date_field_tag :start_date, nil, class: 'form-control' %>
                </div>
                <div style="padding: 5px">
                  <%= label_tag 'Конечная дата' %><br>
                  <%= date_field_tag :end_date, nil, class: 'form-control' %>
                </div>
                <div>
                  <%= label_tag 'Только мои риски' %>
                  <%= check_box_tag :only_my_risks %>
                </div>
                <%= submit_tag "Отфильтровать", class: 'btn btn-primary' %>
              </div>
            </div>
        <% end %>
      </div>
      <div align="center">
        <%= form_tag(controller: :risks, action: :export) do %>
              <div class="card" style="padding: 10px; margin: 8px;">
                <div class="card-block">
                  <div style="padding: 5px">
                    <%= label_tag 'Начальная дата' %><br>
                    <%= date_field_tag :start_date, nil, class: 'form-control' %>
                  </div>
                  <div style="padding: 5px">
                    <%= label_tag 'Конечная дата' %><br>
                    <%= date_field_tag :end_date, nil, class: 'form-control' %>
                  </div>
                  <div>
                    <%= label_tag 'Только мои риски' %>
                    <%= check_box_tag :only_my_risks %>
                  </div>
                  <%= submit_tag "CSV", value: 'csv', name: 'format', class: 'btn btn-primary' %>
                  <%= submit_tag "XLS", value: 'xls', name: 'format', class: 'btn btn-primary' %>
                  <%= submit_tag "XLSX", value: 'xlsx', name: 'format', class: 'btn btn-primary' %>
                </div>
              </div>
        <% end %>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="card" style="padding: 10px; margin: 8px;">
        <div class="card-block">
          <h2 align="center">Распределение по источникам</h2>
          <%= pie_chart [
                            [
                                'Внутренний',
                                @risks.where(origin_type: :internal).count
                            ],
                            [
                                'Внешний',
                                @risks.where(origin_type: :external).count
                            ]
                        ]  %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card" style="padding: 10px; margin: 8px;">
        <div class="card-block">
          <h2 align="center">Распределение по уровню критичности</h2>
          <%= pie_chart @risks.group(:danger_rate).count %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="card" style="padding: 10px; margin: 8px;">
        <div class="card-block">
          <h2 align="center">Распределение по дате для каждого источника</h2>
          <%= line_chart line_chart_data, xtitle: "Дата", ytitle: "Количество"  %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card" style="padding: 10px; margin: 8px;">
        <div class="card-block">
          <h2 align="center">Диаграмма рассеяния "Критичность-встречаемость"</h2>
          <%= scatter_chart scatter_data, xtitle: "Встречаемость", ytitle: "Критичность"%>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= image_tag 'logo.svg', style: 'max-width: 150px;' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Главная', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Риски', risks_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Мой профиль', user_path(current_user), class: "nav-link" %>
      </li>
      <form class="form-inline my-2 my-lg-0">
        <%= link_to 'Добавить риск', new_risk_path, class: "btn btn-outline-primary my-2 my-sm-0" %>
      </form>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
              <li><%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
                    <i class="glyphicon glyphicon-log-out"></i>&nbsp; Выйти
                <% end %>
              </li>
          <% else %>
              <li><%= link_to new_user_session_path, class: 'nav-link' do %>
                    <i class="glyphicon glyphicon-log-in"></i>&nbsp; Войти
                <% end %>
              </li>
              <li><%= link_to new_user_registration_path, class: 'nav-link' do %>
                    <i class="glyphicon glyphicon-plus"></i>&nbsp; Регистрация
                <% end %>
              </li>
          <% end %>
        </ul>
      </div>
    </ul>
  </div>
</nav>

app/views/users/show.html.erb
<h1>Мой профиль</h1>
<div class="col-md-3">
  <% if @user.avatar.nil? %>
    <%= image_tag 'default_avatars/man128.png', class: 'img-responsive' %>
  <% else %>
    <%= image_tag @user.avatar, class: 'img-responsive' %>
  <% end %>
</div>
<div class="col-md-6">
  <div>
    <h1><%= @user.name %></h1>
  </div>
  <div>
    <h1><%= @user.surname %></h1>
  </div>
</div>